// <auto-generated />
using System;
using Clasess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clasess.Migrations
{
    [DbContext(typeof(SubDbContext))]
    [Migration("20260125231306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Clasess.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Clasess.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "amount");

                    b.Property<bool>("AutoPayment")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "auto_payment");

                    b.Property<string>("BillingCycle")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "billing_cycle");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "currency");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "is_trial");

                    b.Property<DateTime>("NextBillingDate")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "next_billing_date");

                    b.Property<int>("Recordatorio")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "reminder_days");

                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "service_name");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("Clasess.Payment", b =>
                {
                    b.HasOne("Clasess.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Clasess.Subscription", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
